fall_model: "models/fall_detector.pt"
fire_model: "models/fire_detector.pt"
fall_confidence: 0.7
fire_confidence: 0.5
spill_confidence: 0.6
roboflow_api_key: "s2NbvQbuGUav8oYF9e7Z" # Your Roboflow API Key
spill_detection_interval: 30 # Run spill detection every 30th time the agent is processed
evidence_path: "data/evidence" # Directory to save event snapshots
